export { Header } from './Header'
export { Hero } from './Hero'
export { About } from './About'
export { Tokenomics } from './tokenomics'
export { Airdrop } from './airdrop'
export { Presale } from './presale'
