export { Header } from "./Header";
export { Hero } from "./Hero";
export { About } from "./About";
export { Tokenomics } from "./Tokenomics";
export { Airdrops } from "./Airdrops";
export { Presale } from "./Presale";
export { RoadMap } from "./RoadMap";
export { Team } from "./Team";
export { GeneralOverview } from "./GeneralOverview";
